In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('Results.csv')
df

,RACE DATE,RACE NAME,PLACEMENT,BIB #,NAME,GRADE,SCHOOL,SCORE,HEAT #,POINTS,MS,INCHES
0,4/13/25,Girls 2&U 100 Meter Dash,1,575,"Horowitz, Ava",2,John Paul,16.01,7.0,10.0,16001,16.01
1,4/13/25,Girls 2&U 100 Meter Dash,2,354,"Daiga, Astrid",1,SMSG,16.55,5.0,8.0,16055,16.55
2,4/13/25,Girls 2&U 100 Meter Dash,3,481,"Brennan, Abigail",2,Joseph YORK,16.57,7.0,6.0,16057,16.57
3,4/13/25,Girls 2&U 100 Meter Dash,4,2,"Duffell, Jenny",K,Annunciation,16.61,7.0,5.0,16061,16.61
4,4/13/25,Girls 2&U 100 Meter Dash,5,576,"Offurum, Olanma",2,John Paul,16.78,6.0,4.0,16078,16.78
...,...,...,...,...,...,...,...,...,...,...,...,...
3037,6/1/25,Boys 7-8 Javelin Throw,10,352,"McDonald, Tristan",7,SFDC,36-00,NaN,NaN,0,432.00
3038,6/1/25,Boys 7-8 Javelin Throw,11,140,"Arteaga, Matias",7,IONA,33-03,NaN,NaN,0,399.00
3039,6/1/25,Boys 7-8 Javelin Throw,12,152,"Tietz, Jake",7,IONA,32-05,NaN,NaN,0,389.00
3040,6/1/25,Boys 7-8 Javelin Throw,13,405,"Higgins, Brody",7,SMSG,29-07,NaN,NaN,0,355.00
3041,6/1/25,Boys 7-8 Javelin Throw,14,406,"Pateno, Xian Anth",7,SMSG,23-02,NaN,NaN,0,278.00

In [28]:
race = df[df['RACE NAME'] == 'Boys 5-6 400 Meter Dash']
race

,RACE DATE,RACE NAME,PLACEMENT,BIB #,NAME,GRADE,SCHOOL,SCORE,HEAT #,POINTS,MS,INCHES
481,4/13/25,Boys 5-6 400 Meter Dash,1,318,"Cabrera, Aiden",5,SFA,1:11.97,5.0,10.0,71097,0.000833
482,4/13/25,Boys 5-6 400 Meter Dash,2,623,"Jack, Don",6,IHM,1:19.21,5.0,8.0,79021,0.000917
483,4/13/25,Boys 5-6 400 Meter Dash,3,595,"Offurum, Arinze",5,John Paul,1:19.44,5.0,6.0,79044,0.000919
484,4/13/25,Boys 5-6 400 Meter Dash,4,559,"Johnson, Peter",6,Stephen,1:19.84,5.0,5.0,79084,0.000924
485,4/13/25,Boys 5-6 400 Meter Dash,5,216,"Lopez, Jazfel",6,MVP,1:20.77,4.0,4.0,80077,0.000935
...,...,...,...,...,...,...,...,...,...,...,...,...
2847,6/1/25,Boys 5-6 400 Meter Dash,5,129,"Wilson, Ethan",5,IONA,1:26.82,4.0,4.0,86082,0.001005
2848,6/1/25,Boys 5-6 400 Meter Dash,6,553,"Higgins, Ronin",5,Stephen,1:28.41,4.0,3.0,88041,0.001023
2849,6/1/25,Boys 5-6 400 Meter Dash,7,554,"Hummel, Julian",5,Stephen,1:34.31,4.0,2.0,94031,0.001092
2850,6/1/25,Boys 5-6 400 Meter Dash,8,552,"Fitzpatrick, Char",5,Stephen,1:41.62,4.0,1.0,101062,0.001176
2851,6/1/25,Boys 5-6 400 Meter Dash,9,339,"Hasanoeddin, Loga",5,SFDC,1:49.87,4.0,NaN,109087,0.001272

In [29]:
avg_time_by_school = race.groupby('SCHOOL')['MS'].mean()
avg_time_by_school

SCHOOL
Annunciation     85037.000000
BARN             91050.000000
CYO Club         81032.000000
Epiphany         93907.571429
IHM              84032.200000
IONA             87856.272727
John Paul        79044.000000
MVP              88595.888889
OL Grace         95060.000000
Patrick          84033.000000
SFA              87788.875000
SFDC             93079.333333
SMSG             79549.750000
Stephen         102007.320000
Name: MS, dtype: float64

In [30]:
race.join(avg_time_by_school, on='SCHOOL', rsuffix='_AVG').sort_values('MS_AVG')

,RACE DATE,RACE NAME,PLACEMENT,BIB #,NAME,GRADE,SCHOOL,SCORE,HEAT #,POINTS,MS,INCHES,MS_AVG
483,4/13/25,Boys 5-6 400 Meter Dash,3,595,"Offurum, Arinze",5,John Paul,1:19.44,5.0,6.0,79044,0.000919,79044.00
486,4/13/25,Boys 5-6 400 Meter Dash,6,397,"Brown, Sean",5,SMSG,1:21.60,5.0,3.0,81060,0.000944,79549.75
1554,5/3/25,Boys 5-6 400 Meter Dash,7,402,"Hilpert-Navas, Lu",6,SMSG,1:26.94,4.0,2.0,86094,0.001006,79549.75
1548,5/3/25,Boys 5-6 400 Meter Dash,1,400,"Abrams, Gabriel",6,SMSG,1:14.07,4.0,10.0,74007,0.000857,79549.75
1065,4/27/25,Boys 5-6 400 Meter Dash,1,400,"Abrams, Gabriel",6,SMSG,1:17.38,6.0,10.0,77038,0.000896,79549.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1560,5/3/25,Boys 5-6 400 Meter Dash,13,557,"Cocozzelli, Sandr",6,Stephen,1:42.25,5.0,NaN,102025,0.001183,102007.32
511,4/13/25,Boys 5-6 400 Meter Dash,31,556,"Zickel, Andrew",5,Stephen,2:02.40,3.0,NaN,122040,0.001417,102007.32
512,4/13/25,Boys 5-6 400 Meter Dash,32,551,"Carriero, John",5,Stephen,2:07.07,3.0,NaN,127007,0.001471,102007.32
1071,4/27/25,Boys 5-6 400 Meter Dash,7,557,"Cocozzelli, Sandr",6,Stephen,1:30.79,6.0,2.0,90079,0.001051,102007.32
1082,4/27/25,Boys 5-6 400 Meter Dash,18,554,"Hummel, Julian",5,Stephen,1:49.80,4.0,NaN,109080,0.001271,102007.32

In [31]:
race['Z_SCORE'] = (race['MS'] - race['MS'].mean()) / race['MS'].std()
race

/var/folders/7_/mbkly6hs1dvdt5855vp4ymh00000gn/T/ipykernel_37705/3719907552.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,RACE DATE,RACE NAME,PLACEMENT,BIB #,NAME,GRADE,SCHOOL,SCORE,HEAT #,POINTS,MS,INCHES,Z_SCORE
481,4/13/25,Boys 5-6 400 Meter Dash,1,318,"Cabrera, Aiden",5,SFA,1:11.97,5.0,10.0,71097,0.000833,-1.757586
482,4/13/25,Boys 5-6 400 Meter Dash,2,623,"Jack, Don",6,IHM,1:19.21,5.0,8.0,79021,0.000917,-1.100760
483,4/13/25,Boys 5-6 400 Meter Dash,3,595,"Offurum, Arinze",5,John Paul,1:19.44,5.0,6.0,79044,0.000919,-1.098854
484,4/13/25,Boys 5-6 400 Meter Dash,4,559,"Johnson, Peter",6,Stephen,1:19.84,5.0,5.0,79084,0.000924,-1.095538
485,4/13/25,Boys 5-6 400 Meter Dash,5,216,"Lopez, Jazfel",6,MVP,1:20.77,4.0,4.0,80077,0.000935,-1.013228
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,6/1/25,Boys 5-6 400 Meter Dash,5,129,"Wilson, Ethan",5,IONA,1:26.82,4.0,4.0,86082,0.001005,-0.515469
2848,6/1/25,Boys 5-6 400 Meter Dash,6,553,"Higgins, Ronin",5,Stephen,1:28.41,4.0,3.0,88041,0.001023,-0.353087
2849,6/1/25,Boys 5-6 400 Meter Dash,7,554,"Hummel, Julian",5,Stephen,1:34.31,4.0,2.0,94031,0.001092,0.143428
2850,6/1/25,Boys 5-6 400 Meter Dash,8,552,"Fitzpatrick, Char",5,Stephen,1:41.62,4.0,1.0,101062,0.001176,0.726233
2851,6/1/25,Boys 5-6 400 Meter Dash,9,339,"Hasanoeddin, Loga",5,SFDC,1:49.87,4.0,NaN,109087,0.001272,1.391430

In [32]:
import datetime

import plotly.express as px

sorted_names = sorted(race['NAME'].unique())

def ms_to_time_str(ms):
  # ms is int, e.g. 87050
  seconds, ms = divmod(ms, 1000)
  minutes, seconds = divmod(seconds, 60)
  hours, minutes = divmod(minutes, 60)
  return f"{int(hours):02}:{int(minutes):02}:{int(seconds):02}.{int(ms):03}"

# Create a new column for formatted time
race['TIME_STR'] = race['MS'].apply(ms_to_time_str)

fig = px.scatter(
  race,
  x='RACE DATE',
  y='MS',
  color='NAME',
  category_orders={'NAME': sorted_names},
  hover_data=['SCHOOL', 'MS', 'TIME_STR'],
  title='Z-Scores by Placement (Colored by Name)'
)

fig.update_yaxes(
  tickvals=race['MS'],
  ticktext=race['MS'].apply(ms_to_time_str),
  title_text='Time (hh:mm:ss.ms)'
)
fig.update_layout(xaxis_title='Placement', yaxis_title='Z-Score')

race = race.sort_values('RACE DATE')
fig.show()

/var/folders/7_/mbkly6hs1dvdt5855vp4ymh00000gn/T/ipykernel_37705/2430740552.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy